/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: N01516 (https://sketchfab.com/N01506)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-camera-5cc60a924f2d4f3a825d3db21ff94613
Title: Vintage Camera
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default forwardRef(function Model(props, ref) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.103}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.836, 3.86, 2.821]} scale={0.447}>
            <mesh geometry={nodes.polySurface684_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface685_lens_dark_0.geometry} material={materials.lens_dark} />
            <mesh geometry={nodes.polySurface686_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface687_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface688_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface689_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface690_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface691_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface691_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface692_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface693_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface694_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface695_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface696_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface697_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface698_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface699_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface700_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface701_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface702_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface703_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface704_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface705_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface706_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface707_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface708_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface709_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface710_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface711_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface712_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface713_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface714_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface715_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface716_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface717_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface718_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface719_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface720_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface721_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface722_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface723_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface724_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface725_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface726_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface727_lens_light_0.geometry} material={materials.lens_light} />
            <mesh geometry={nodes.polySurface728_film_dark_0.geometry} material={materials.film_dark} />
            <mesh geometry={nodes.polySurface728_film_light_0.geometry} material={materials.film_light} />
            <mesh geometry={nodes.polySurface729_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface730_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface731_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface732_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface733_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface734_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface735_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface736_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface737_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface738_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface739_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface740_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface741_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface742_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface743_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface744_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface745_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface746_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface747_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface748_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface749_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface750_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface751_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface752_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface753_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface754_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface755_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface756_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface757_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface758_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface759_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface760_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface761_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface762_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface763_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface764_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface765_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface766_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface767_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface768_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface769_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface769_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface770_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface771_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface772_plastic_yellow_0.geometry} material={materials.plastic_yellow} />
            <mesh geometry={nodes.polySurface773_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface774_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface775_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface776_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface777_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface778_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface779_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface780_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface781_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface782_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface783_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface784_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface785_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface786_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface787_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface788_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface789_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface789_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface790_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface791_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface792_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface793_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface794_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface795_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface796_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface796_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface797_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface798_lens_dark_0.geometry} material={materials.lens_dark} />
            <mesh geometry={nodes.polySurface799_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface800_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface801_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface802_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface803_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface804_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface805_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface806_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface807_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface808_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface809_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface810_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface811_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface812_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface812_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface813_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface814_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface815_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface816_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface817_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface818_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface819_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface820_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface821_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface822_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface823_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface824_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface825_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface826_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface827_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface827_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface828_rubber_black_0.geometry} material={materials.rubber_black} />
            <mesh geometry={nodes.polySurface829_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface830_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface831_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface832_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface833_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface834_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface835_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface836_lens_light_0.geometry} material={materials.lens_light} />
            <mesh geometry={nodes.polySurface837_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface838_plastic_black_gloss_0.geometry} material={materials.plastic_black_gloss} />
            <mesh geometry={nodes.polySurface839_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface840_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface841_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface842_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface843_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface844_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface845_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface846_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface847_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface848_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface849_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface850_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface851_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface852_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface853_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface854_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface855_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface856_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface857_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
            <mesh geometry={nodes.polySurface858_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface859_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface860_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface861_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface862_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface863_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface864_metal_light_0.geometry} material={materials.metal_light} />
            <mesh geometry={nodes.polySurface865_plastic_dark_rough_0.geometry} material={materials.plastic_dark_rough} />
          </group>
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/scene.gltf')
